### ISSUE TITLE
gates

### ISSUE THREAD

**Issue by abrunton80** [joeSeggiola/eurorack#1]
Hi there, I've just downloaded your firmware and flashed it to my Stages. First, I want to say thank you for making this available. I recently bought this module used and it didn't come with the jumper cable, so I haven't been able to try the easter egg until now. 

I had a little trouble getting the levels right when playing the wav file out of my usb interface and into the stages, but eventually got it to register and successfully load the firmware. 

Everything seems to work normally, except the gates in the two ouroboros modes. According to your notes, a gate is supposed to strum the partial for that segment, but I can only seem to get drone notes from each segment. I have tried generate gates, triggers and envelopes from Pam's New Workout, Tides v2, and my keystep. nothing seems to have any effect. 

The gates seem to work fine on the stock mode, even with your firmware, so I don't think it's a problem with the module itself.

Am I doing something wrong? Am I possibly misunderstanding something? Any thoughts on what might be going on? I'm relatively new to modular so it's possible this is a me problem.

Thanks for any help you can provide.

Andy

**Comment by joeSeggiola** [comment]
Hi. In harmonic oscillator mode, the bottom output of columns from 2 to 6 is always a full-volume drone of the selected harmonic. The "strum" is only audible from the main output of column 1, mixed with the root note.

Try this: set all sliders from 2 to 6 to minimum, and monitor audio output of column 1. You should hear only the root note. Now send a gate to column 2, for example, while keeping listening to the column 1 output. You should hear the partial coming in for a short time (like a fast R-envelope).

**Comment by abrunton80** [comment]
Yes, I did finally figure this out when I gated ALL the columns. Then I could hear the space between them. I wasn't hearing the strums because they were lost in the midst of all the drones. Thanks for your response.
